# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- '*'

stages:
  - stage: test
    jobs:
      - job: 'validateandtest'
        pool:
          vmimage: ubuntu-latest
        steps:
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: 'Rajubhai'
              subscriptionId: '1fc9145f-81cc-42cc-b393-94cda14865d6'
              action: 'Create Or Update Resource Group'
              resourceGroupName: 'devpipeline'
              location: 'UK West'
              templateLocation: 'Linked artifact'
              csmFile: '$(Build.SourcesDirectory)/StorageAccount/azuredeploy.json'
              csmParametersFile: '$(Build.SourcesDirectory)/StorageAccount/azuredeploy.parameters.json'
              deploymentMode: 'Validation'
          - task: AzurePowerShell@5
            inputs:
              azureSubscription: 'Rajubhai'
              ScriptType: 'InlineScript'
              Inline: 'Install-Module Az.Resources -RequiredVersion 1.12.1-preview -AllowPrerelease -Force -Scope CurrentUser'
              FailOnStandardError: true
              azurePowerShellVersion: 'LatestVersion'
          - task: AzurePowerShell@5
            displayname: "deletion"
            inputs:
              azureSubscription: 'Rajubhai'
              ScriptType: 'FilePath'
              ScriptPath: '$(Build.SourcesDirectory)/Tests/CheckForDeletion.ps1'
              ScriptArguments: 'ResourceGroup ARMDeploymentTest'
              FailOnStandardError: true
              azurePowerShellVersion: 'LatestVersion'